apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- gotk-components.yaml
- gotk-sync.yaml
- limit-range.yaml
- resource-quota.yaml
patchesStrategicMerge:
- gotk-components-patch.yaml
images:
- name: ghcr.io/fluxcd/source-controller
  newName: acrakslsuoccqde6qa2.azurecr.io/fluxcd/source-controller
- name: ghcr.io/fluxcd/kustomize-controller
  newName: acrakslsuoccqde6qa2.azurecr.io/fluxcd/kustomize-controller
