apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster-baseline-settings
resources:
- namespace.yaml
- resource-quota.yaml
- networkpolicy-denyall.yaml
- limit-range.yaml
- rbac.yaml
- fim-standin.yaml
- av-standin.yaml
- kured.yaml
images:
- name: busybox
  newName: REPLACE_ME_WITH_YOUR_ACRNAME.azurecr.io/library/busybox
  newTag: 1.33.0
- name: docker.io/weaveworks/kured
  newName: REPLACE_ME_WITH_YOUR_ACRNAME.azurecr.io/weaveworks/kured
